Implement the ability to add a pinned footer to the LazyTable.
oleksandrbalan/lazytable pull request #19
Opened 2024-01-11 17:58 UTC by mattgraham1

Issue: #17 

Description:
Implemented the ability to add a pinned footer row to a LazyTable. Updated the configuration to allow consumers to set a footer flag indicating to pin a footer row. We also updated the MinaBox call within the LazyTable to pass the table height to the `toMineBoxItem` extension function and added an extra item to push the second to last row up when accounting for a pinned footer row. Within the `toMineBoxItem` extension function we accounted for adjusting the `y` coordinate and how `lockVertically` is set. Last, we bumped the version to `1.7.0` as this should not be a breaking change but adding additional functionality.

Evidence of changes:
- Do note, I wasn't able to run the iOS app successfully as I was getting coroutine exception thrown.

2024-01-22 23:04 UTC, oleksandrbalan requested changes
Just a few nitpicks 👀 

Thx once more 👍 

Also take a look on a "spotless" action result, you could also run it locally: 
`./gradlew spotlessCheck` (or `./gradlew spotlessApply` to auto-apply suggestions)

2024-01-23 03:58 UTC, mattgraham1 commented on demo/src/commonMain/kotlin/eu/wewox/lazytable/screens/LazyTablePinnedScreen.kt
> +    val showFooter: Boolean = true,
Good call, refactor `showFoote`r boolean to be initialized to false in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c.

2024-01-23 03:58 UTC, mattgraham1 commented on gradle.properties
> +VERSION_NAME=1.7.0
Reverted in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c.

2024-01-23 03:59 UTC, mattgraham1 commented on lazytable/src/commonMain/kotlin/eu/wewox/lazytable/LazyTable.kt
> +        val newTableHeight = dimensionsPx.rowsSize.sum()
Refactored min() call out of each item in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c.

2024-01-23 04:01 UTC, mattgraham1 commented on lazytable/src/commonMain/kotlin/eu/wewox/lazytable/LazyTable.kt
> +        ZIndexPinnedCorner
Created a new ZIndex item to 3f in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c. I had to keep the logic of both `pinnedColumn && pinnedFooter`. If I only used `pinnedFooter` when scrolling from right to left the first of second pinned column title row cells wouldn't stay pinned and be over lapped by cells from the right.

2024-01-23 04:01 UTC, mattgraham1 commented on lazytable/src/commonMain/kotlin/eu/wewox/lazytable/LazyTablePinConfiguration.kt
> + * @property footer The flag for showing a pinned footer.
Good catch! Probably a good ole cut and paste error there I'm sure. Refactored in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c.

2024-01-23 04:02 UTC, mattgraham1 commented
> Just a few nitpicks 👀
> 
> Thx once more 👍
> 
> Also take a look on a "spotless" action result, you could also run it locally: `./gradlew spotlessCheck` (or `./gradlew spotlessApply` to auto-apply suggestions)

Ran the spotless check and applied the suggested changes in commit c72e4c3b4ada93373d8e93fff7759b9214f17e5c.

2024-01-23 06:24 UTC, oleksandrbalan approved these changes

2024-01-23 06:24 UTC, oleksandrbalan commented
> > Just a few nitpicks 👀
> > Thx once more 👍
> > Also take a look on a "spotless" action result, you could also run it locally: `./gradlew spotlessCheck` (or `./gradlew spotlessApply` to auto-apply suggestions)
> 
> Ran the spotless check and applied the suggested changes in commit [c72e4c3](https://github.com/oleksandrbalan/lazytable/commit/c72e4c3b4ada93373d8e93fff7759b9214f17e5c).

Awesome, many thanks! :+1:

2024-01-23 06:25 UTC, merged